### ISSUE TITLE
Creates empty report while compiled with OCaml 4.05

### ISSUE THREAD

**Issue by pirbo** [lpw25/prof_alloc#18]
I compiled an executable using 4.04.2+spacetime and 4.05.0+spacetime opam switches and I ran it. In both cases, the run has generated a ~100 Mo `spacetime-*` file.
Then, I installed `prof_spacetime.0.1.0` in 4.04.2 switch, processing the reports generates ~100Mo `spacetime-*.p` files, serving/viewing them allows me to analyse them. Nice ! (I'm not sure, it is expected that 4.04.2 prof_spacetime is able to analyse report of 4.05.0+spacetime but it works...)

Now,
if I go in switch 4.05.0 and I install either spacetime_lib.0.1+prof_spacetime.0.1 or spacetime_lib.0.2~dev+prof_spacetime.0.2~dev, when I try to process my 2 (working in 4.04.2) reports, there is no visible crash but I obtain ~100 ko `spacetime-*.p` files that are "empty" when I serve/view/print them! (Trying to serve/view/print them directly without the independent "process" phase leads to the same result)

**Comment by lpw25** [comment]
This is a bug in the compiler. I've submitted a PR to fix it in 4.06: 

https://github.com/ocaml/ocaml/pull/1407
