### ISSUE TITLE
Only see small amount of profile data

### ISSUE THREAD

**Issue by psteckler** [lpw25/prof_alloc#24]
After a long execution, I see only a small amount of profile data using `view` or `serve`.

Posted this to `ocaml.discuss`, also: https://discuss.ocaml.org/t/width-of-spacetime-analysis-window/4355

Maybe this is an issue with the generated data, rather than `prof_spacetime` as such.

**Comment by lpw25** [comment]
The time shown is a sum of user and sys time, not wall clock time, so you probably have data for your whole execution just not labeled as you expect.

**Comment by psteckler** [comment]
Thanks, I did see that mentioned in the docs somewhere.
