### ISSUE TITLE
print "Serving" message with a real url

### ISSUE THREAD

**Issue by c-cube** [lpw25/prof_alloc#3]
Right now, it looks like:
`Serving on 127.0.0.1:8080`

but it would be better as:
`Serving on http://127.0.0.1:29255`

so it becomes easier to select/open it. In fact, if "$BROWSER" is defined it could perhaps even open the url automatically…

**Comment by lpw25** [comment]
Should be addressed by https://github.com/lpw25/prof_spacetime/commit/7ceab9b1b5669c1dcb7e49e4dbce4f648fd47230.
